// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import GalleryController from "./gallery_controller"
application.register("gallery", GalleryController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageCompressionController from "./image_compression_controller"
application.register("image-compression", ImageCompressionController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import TasteAdvisorController from "./taste_advisor_controller"
application.register("taste-advisor", TasteAdvisorController)
